CREATE TABLE USERS (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL
);

CREATE TABLE USER_DETAILS (
    ID NUMBER PRIMARY KEY,
    ADDRESS VARCHAR2(255),
    PHONE VARCHAR2(20),
    USER_ID NUMBER UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);


SELECT * FROM employees;

SELECT first_name, last_name, department_name 
FROM employees JOIN departments
USING(department_id);

SELECT * FROM departments;

SELECT d.department_id, d.department_name, e.first_name, e.last_name 
FROM departments d JOIN employees e
ON (d.manager_id = e.employee_id);
